#!/bin/bash

# Project Backup Script
# Generated by Ultimate Project Generator

PROJECT_NAME=$(basename "$(pwd)")
BACKUP_DIR="$HOME/project-backups"
TIMESTAMP=$(date +"%Y%m%d_%H%M%S")
BACKUP_NAME="${PROJECT_NAME}_${TIMESTAMP}"

echo "💾 PROJECT BACKUP"
echo "================="
echo "Project: $PROJECT_NAME"
echo "Backup: $BACKUP_NAME"
echo ""

# Create backup directory
mkdir -p "$BACKUP_DIR"

# Create backup archive
echo "📦 Creating backup archive..."
tar -czf "$BACKUP_DIR/${BACKUP_NAME}.tar.gz" \
    --exclude='.git' \
    --exclude='node_modules' \
    --exclude='dist' \
    --exclude='build' \
    --exclude='.cache' \
    --exclude='*.log' \
    .

if [ $? -eq 0 ]; then
    echo "✅ Backup created successfully!"
    echo "📍 Location: $BACKUP_DIR/${BACKUP_NAME}.tar.gz"
    
    # Show backup size
    BACKUP_SIZE=$(du -sh "$BACKUP_DIR/${BACKUP_NAME}.tar.gz" | cut -f1)
    echo "📏 Size: $BACKUP_SIZE"
    
    # Clean old backups (keep last 5)
    echo ""
    echo "🧹 Cleaning old backups..."
    cd "$BACKUP_DIR"
    ls -t ${PROJECT_NAME}_*.tar.gz | tail -n +6 | xargs -r rm
    echo "✅ Cleanup complete"
    
    # List all backups for this project
    echo ""
    echo "📋 Available backups:"
    ls -lh ${PROJECT_NAME}_*.tar.gz 2>/dev/null || echo "No backups found"
    
else
    echo "❌ Backup failed!"
    exit 1
fi
